import { ChatOpenAI } from "@langchain/openai";
import { ToolConfig, MCPServerConfig } from "../types/constants";

// ============================================================================
// GRAPH STATE TYPES
// ============================================================================

/**
 * The standard user-defined state maintained during a LangGraph execution.
 * Represents the dynamic memory schema passed between nodes.
 */
export type GraphState = Record<string, unknown>;

/**
 * The internal state representation used by the runtime engine.
 * Includes reserved system channels used for routing, error handling,
 * and Human-in-the-Loop (HITL) feedback.
 */
export interface InternalGraphState {
  /** The final synthesized output payload to be returned to the client */
  __final_payload__?: unknown;
  /** System-level or tool-level errors caught during node execution */
  __error__?: string;
  /** Feedback or input injected by a user when resuming from an interrupted state */
  __human_feedback__?: unknown;
  /** User-defined state variables */
  [key: string]: unknown;
}

// ============================================================================
// MANIFEST & TOPOLOGY TYPES
// ============================================================================

/**
 * Represents a discrete, executable step in the orchestration graph.
 * @template TData - The expected shape of the node's configuration data.
 */
export interface ManifestNode<TData = Record<string, unknown>> {
  id: string;
  type: "trigger" | "response" | "tool" | "mcp_node" | "interrupt";
  data: TData;
}

/**
 * Represents a directional edge (connection) between two nodes.
 * Used for both unconditional routing and natural language conditional routing.
 */
export interface ManifestEdge {
  source: string;
  target: string;
  data?: {
    /** The natural language condition evaluated by the edge router */
    label?: string;
  };
}

export type ResolvedSkillConfig = Pick<
  ToolConfig,
  "name" | "prompt_template" | "input_schema" | "output_schema"
>;

export type ResolvedServerConfig = Pick<
  MCPServerConfig,
  "name" | "url" | "auth_type"
>;

/**
 * The fully resolved, static configuration required to execute an agent workflow.
 * Generated by the Manifest Compiler prior to execution.
 */
export interface CompiledManifest {
  metadata: {
    skill_id: string;
    version: string;
    description: string;
  };
  engine: {
    model: { model_name: string; temperature: number };
    system_prompt: string;
    state_schema: Record<string, string>;
  };
  /** Standardized prompt templates used by system nodes (e.g., router, formatter) */
  engine_prompts: Record<string, string>;
  /** The subset of LLM tools actively used by the graph */
  resolved_skills: Record<string, ResolvedSkillConfig>;
  /** The subset of remote MCP servers actively used by the graph */
  resolved_mcp_servers: Record<string, ResolvedServerConfig>;
  graph_topology: {
    nodes: ManifestNode[];
    edges: ManifestEdge[];
  };
}

// ============================================================================
// EXECUTION & CONTEXT TYPES
// ============================================================================

/**
 * Standardized callback hooks for monitoring and streaming graph execution events.
 * Used by the UI playground and upstream APIs to track real-time agent reasoning.
 */
export interface ManifestExecutionReporter {
  onNodeStart?: (nodeName: string) => void;
  onNodeEnd?: (
    nodeName: string,
    stateUpdates: GraphState,
    reasoning?: string,
    fullState?: GraphState,
  ) => void;
  onEdgeTraversal?: (
    sourceName: string,
    targetName: string,
    condition?: string,
    reasoning?: string,
  ) => void;
  onToolStart?: (toolName: string, args: GraphState) => void;
  onToolEnd?: (toolName: string, result: unknown) => void;
}

/**
 * The shared execution context injected into every node factory.
 * Provides nodes with access to the LLM, the full manifest, and event reporting.
 */
export interface NodeContext {
  manifest: CompiledManifest;
  /** * The active LLM instance.
   * Note: Could be widened to `BaseChatModel` if multiple providers (e.g., Anthropic) are supported.
   */
  llm: ChatOpenAI;
  reporter?: ManifestExecutionReporter;
  edges: ManifestEdge[];
  /** Helper to retrieve the human-readable label of a node by its ID */
  getLabel: (id: string) => string;
  /** The top-level persona/instructions governing the agent */
  globalPersona: string;
}
